# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koledarji', '0003_calendar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
