# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koledarji', '0004_auto_20161220_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
